version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: instantShare/Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    env_file:
      - ./.env
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
